// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKepWSjnwXO7yXPs1yDeHEBNV2kt0ZlTY',
    appId: '1:593635657853:web:94e2916a76aaf43ccb8914',
    messagingSenderId: '593635657853',
    projectId: 'chatting-app-9b854',
    authDomain: 'chatting-app-9b854.firebaseapp.com',
    storageBucket: 'chatting-app-9b854.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFxvqPPQQcCEXhoKx8HPKLCvkQP4aJyZ4',
    appId: '1:593635657853:android:bbd37b12acad5826cb8914',
    messagingSenderId: '593635657853',
    projectId: 'chatting-app-9b854',
    storageBucket: 'chatting-app-9b854.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAV09-YGjJViIDVtQ2Mq0DGiQfJhLBMyO8',
    appId: '1:593635657853:ios:2843175af2f6ccb9cb8914',
    messagingSenderId: '593635657853',
    projectId: 'chatting-app-9b854',
    storageBucket: 'chatting-app-9b854.firebasestorage.app',
    iosBundleId: 'com.example.chattingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAV09-YGjJViIDVtQ2Mq0DGiQfJhLBMyO8',
    appId: '1:593635657853:ios:2843175af2f6ccb9cb8914',
    messagingSenderId: '593635657853',
    projectId: 'chatting-app-9b854',
    storageBucket: 'chatting-app-9b854.firebasestorage.app',
    iosBundleId: 'com.example.chattingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKepWSjnwXO7yXPs1yDeHEBNV2kt0ZlTY',
    appId: '1:593635657853:web:61d76970ed1b9f4acb8914',
    messagingSenderId: '593635657853',
    projectId: 'chatting-app-9b854',
    authDomain: 'chatting-app-9b854.firebaseapp.com',
    storageBucket: 'chatting-app-9b854.firebasestorage.app',
  );
}
